src/main/java/sopt/appjam/withsuhyeon/global/base/BaseResponse.java
src/main/java/sopt/appjam/withsuhyeon/global/exception/BaseException.java
src/main/java/sopt/appjam/withsuhyeon/global/exception/CustomErrorResponse.java
src/main/java/sopt/appjam/withsuhyeon/global/exception/ErrorCode.java
src/main/java/sopt/appjam/withsuhyeon/global/exception/GlobalErrorCode.java
src/main/java/sopt/appjam/withsuhyeon/global/exception/GlobalExceptionHandler.java
src/main/java/sopt/appjam/withsuhyeon/global/interceptor/post/ResponseInterceptor.java

✨ [FEAT] CustomResponse 구현

---

src/main/java/sopt/appjam/withsuhyeon/WithsuhyeonApplication.java
src/main/java/sopt/appjam/withsuhyeon/constant/Age.java
src/main/java/sopt/appjam/withsuhyeon/constant/Category.java
src/main/java/sopt/appjam/withsuhyeon/constant/Profile.java
src/main/java/sopt/appjam/withsuhyeon/constant/Region.java
src/main/java/sopt/appjam/withsuhyeon/constant/Request.java
src/main/java/sopt/appjam/withsuhyeon/domain/AgeEntity.java
src/main/java/sopt/appjam/withsuhyeon/domain/BlockEntity.java
src/main/java/sopt/appjam/withsuhyeon/domain/CategoryEntity.java
src/main/java/sopt/appjam/withsuhyeon/domain/GalleryEntity.java
src/main/java/sopt/appjam/withsuhyeon/domain/PostEntity.java
src/main/java/sopt/appjam/withsuhyeon/domain/RequestEntity.java
src/main/java/sopt/appjam/withsuhyeon/domain/UserEntity.java

✨  [FEAT]  #2 도메인 생성

---

src/main/java/sopt/appjam/withsuhyeon/constant/Age.java
src/main/java/sopt/appjam/withsuhyeon/constant/Category.java
src/main/java/sopt/appjam/withsuhyeon/constant/ProfileImage.java
src/main/java/sopt/appjam/withsuhyeon/constant/Region.java
src/main/java/sopt/appjam/withsuhyeon/constant/RequestInfo.java
src/main/java/sopt/appjam/withsuhyeon/domain/UserEntity.java

✨ [FEAT] ENUM 수정

---

src/main/java/sopt/appjam/withsuhyeon/controller/AuthController.java
src/main/java/sopt/appjam/withsuhyeon/controller/UserController.java
src/main/java/sopt/appjam/withsuhyeon/domain/BlockEntity.java
src/main/java/sopt/appjam/withsuhyeon/domain/UserEntity.java
src/main/java/sopt/appjam/withsuhyeon/dto/auth/req/SignupRequestDto.java
src/main/java/sopt/appjam/withsuhyeon/dto/user/req/BlockNumberRequestDto.java
src/main/java/sopt/appjam/withsuhyeon/repository/BlockRepository.java
src/main/java/sopt/appjam/withsuhyeon/repository/UserRepository.java
src/main/java/sopt/appjam/withsuhyeon/service/UserService.java

- closes #14
- 확인해야 할 사항
- 전화번호 차단 시 자기 번호를 차단하는 경우
- 차단 조회 시, 차단된 연락처 개수도 내려줘야 하는지?
- 차단 삭제 시, 쿼리 파라미터 추가 (전화번호)
- 차단 연락처 삭제 시에 x 버튼 누를 때 차단 삭제할 번호를 받아서 삭제
조회까지 하려고 했는데, 정전 이슈 때문에 여기까지만 합니당,,ㅎ

✨ [FEAT] 번호 차단 API 구현

---

src/main/java/sopt/appjam/withsuhyeon/controller/AuthController.java
src/main/java/sopt/appjam/withsuhyeon/controller/BlockController.java
src/main/java/sopt/appjam/withsuhyeon/controller/UserController.java
src/main/java/sopt/appjam/withsuhyeon/dto/block/req/BlockNumberRequestDto.java
src/main/java/sopt/appjam/withsuhyeon/dto/block/res/BlockNumberListResponseDto.java
src/main/java/sopt/appjam/withsuhyeon/dto/user/req/BlockNumberListResponseDto.java
src/main/java/sopt/appjam/withsuhyeon/exception/BlockErrorCode.java
src/main/java/sopt/appjam/withsuhyeon/repository/BlockRepository.java
src/main/java/sopt/appjam/withsuhyeon/service/BlockService.java
src/main/java/sopt/appjam/withsuhyeon/service/UserService.java

✨ [FEAT] 차단 번호 조회 API 구현

---

src/main/java/sopt/appjam/withsuhyeon/controller/AuthController.java
src/main/java/sopt/appjam/withsuhyeon/dto/auth/req/SignInRequestDto.java
src/main/java/sopt/appjam/withsuhyeon/dto/auth/req/SignUpRequestDto.java
src/main/java/sopt/appjam/withsuhyeon/dto/auth/res/JwtTokensDto.java
src/main/java/sopt/appjam/withsuhyeon/repository/UserRepository.java
src/main/java/sopt/appjam/withsuhyeon/service/AuthService.java
src/main/java/sopt/appjam/withsuhyeon/service/UserService.java

✨ [FEAT] 회원가입/로그인 구현

---

src/main/java/sopt/appjam/withsuhyeon/constant/Age.java
src/main/java/sopt/appjam/withsuhyeon/constant/Region.java
src/main/java/sopt/appjam/withsuhyeon/constant/RequestInfo.java
src/main/java/sopt/appjam/withsuhyeon/controller/PostController.java
src/main/java/sopt/appjam/withsuhyeon/domain/PostEntity.java
src/main/java/sopt/appjam/withsuhyeon/dto/post/req/PostRequestDto.java
src/main/java/sopt/appjam/withsuhyeon/exception/PostErrorCode.java
src/main/java/sopt/appjam/withsuhyeon/repository/PostRepository.java
src/main/java/sopt/appjam/withsuhyeon/repository/RequestRepository.java
src/main/java/sopt/appjam/withsuhyeon/service/PostService.java

✨ [FEAT] 수현이 찾기 게시글 등록 API 구현

---

src/main/java/sopt/appjam/withsuhyeon/controller/PostController.java
src/main/java/sopt/appjam/withsuhyeon/exception/PostErrorCode.java
src/main/java/sopt/appjam/withsuhyeon/repository/PostRepository.java
src/main/java/sopt/appjam/withsuhyeon/repository/RequestRepository.java
src/main/java/sopt/appjam/withsuhyeon/service/PostService.java

:sparkles: [FEAT] 수현이 찾기 게시글 삭제 API

---

src/main/java/sopt/appjam/withsuhyeon/controller/UserController.java
src/main/java/sopt/appjam/withsuhyeon/dto/user/res/UserInfoResponse.java
src/main/java/sopt/appjam/withsuhyeon/service/UserService.java

:sparkles: [FEAT] 마이페이지 조회 API

---

src/main/java/sopt/appjam/withsuhyeon/constant/Region.java
src/main/java/sopt/appjam/withsuhyeon/controller/ConstantController.java
src/main/java/sopt/appjam/withsuhyeon/dto/constant/res/Regions.java
src/main/java/sopt/appjam/withsuhyeon/dto/constant/res/RegionsResponse.java

:sparkles: [FEAT] 전체 활동 지역 조회

---

src/main/java/sopt/appjam/withsuhyeon/constant/Category.java
src/main/java/sopt/appjam/withsuhyeon/controller/GalleryController.java
src/main/java/sopt/appjam/withsuhyeon/dto/gallery/req/CreateGalleryRequest.java
src/main/java/sopt/appjam/withsuhyeon/exception/ConstantErrorCode.java
src/main/java/sopt/appjam/withsuhyeon/exception/GalleryErrorCode.java
src/main/java/sopt/appjam/withsuhyeon/repository/GalleryRepository.java
src/main/java/sopt/appjam/withsuhyeon/service/GalleryService.java

- closes #49 
`GalleryService` 에서 MultipartFile 을 URL로 변경하는 로직을 추가해주세요.

[FEAT] 갤러리 작성 API 간단 구현

---

src/main/java/sopt/appjam/withsuhyeon/constant/Category.java
src/main/java/sopt/appjam/withsuhyeon/controller/ConstantController.java
src/main/java/sopt/appjam/withsuhyeon/controller/GalleryController.java
src/main/java/sopt/appjam/withsuhyeon/dto/gallery/res/GalleriesListResponse.java
src/main/java/sopt/appjam/withsuhyeon/dto/gallery/res/GalleryDetailResponse.java
src/main/java/sopt/appjam/withsuhyeon/dto/gallery/res/GalleryResponse.java
src/main/java/sopt/appjam/withsuhyeon/repository/GalleryRepository.java
src/main/java/sopt/appjam/withsuhyeon/service/GalleryService.java

✨ [FEAT] 갤러리 조회/삭제 API 간단 구현

---

src/main/java/sopt/appjam/withsuhyeon/controller/BlockController.java
src/main/java/sopt/appjam/withsuhyeon/controller/UserController.java
src/main/java/sopt/appjam/withsuhyeon/dto/user/res/UserIdResponse.java

✨ [FEAT] 유저 id 조회 API 구현

---

build.gradle
src/main/java/sopt/appjam/withsuhyeon/config/S3Client.java

:sparkles: [FEAT] S3Client 구현

---

src/main/java/sopt/appjam/withsuhyeon/domain/GalleryEntity.java
src/main/java/sopt/appjam/withsuhyeon/exception/FileErrorCode.java
src/main/java/sopt/appjam/withsuhyeon/service/GalleryService.java
src/main/java/sopt/appjam/withsuhyeon/util/FileConvertUtil.java

✨ [FEAT] 갤러리 작성 API 구현

---

src/main/java/sopt/appjam/withsuhyeon/WithsuhyeonApplication.java
src/main/java/sopt/appjam/withsuhyeon/config/S3Config.java
src/main/java/sopt/appjam/withsuhyeon/service/GalleryService.java

🐛 [FIX] 갤러리 등록 API 버그 수정

---

src/main/java/sopt/appjam/withsuhyeon/constant/Category.java

✨ [FEAT] 카테고리 태그 변경하기

---

src/main/java/sopt/appjam/withsuhyeon/constant/Region.java
src/main/java/sopt/appjam/withsuhyeon/controller/PostController.java
src/main/java/sopt/appjam/withsuhyeon/domain/PostEntity.java
src/main/java/sopt/appjam/withsuhyeon/exception/BlockErrorCode.java
src/main/java/sopt/appjam/withsuhyeon/exception/ConstantErrorCode.java
src/main/java/sopt/appjam/withsuhyeon/repository/BlockRepository.java
src/main/java/sopt/appjam/withsuhyeon/repository/PostRepository.java
src/main/java/sopt/appjam/withsuhyeon/service/BlockService.java
src/main/java/sopt/appjam/withsuhyeon/service/PostService.java

:sparkles: [FEAT] 수현이 찾기 게시글 차단 필터링

---

build.gradle
src/main/java/sopt/appjam/withsuhyeon/config/MessageServiceConfig.java
src/main/java/sopt/appjam/withsuhyeon/config/RedisConfig.java
src/main/java/sopt/appjam/withsuhyeon/constant/AuthConstant.java
src/main/java/sopt/appjam/withsuhyeon/controller/SMSMessageController.java
src/main/java/sopt/appjam/withsuhyeon/dto/sms/req/CertificationPhoneNumberRequest.java
src/main/java/sopt/appjam/withsuhyeon/dto/sms/req/VerifyCertificationNumberRequest.java
src/main/java/sopt/appjam/withsuhyeon/exception/RedisErrorCode.java
src/main/java/sopt/appjam/withsuhyeon/exception/UserErrorCode.java
src/main/java/sopt/appjam/withsuhyeon/repository/UserRepository.java
src/main/java/sopt/appjam/withsuhyeon/service/SMSMessageService.java

✨ [FEAT] 번호인증 API 구현

---

src/main/java/sopt/appjam/withsuhyeon/dto/post/res/PostDetailResponse.java
src/main/java/sopt/appjam/withsuhyeon/service/PostService.java

:sparkles: [FEAT]게시글 상세 조회 기간 만료 상태 추가

---

src/main/java/sopt/appjam/withsuhyeon/security/config/SecurityConfig.java
src/main/java/sopt/appjam/withsuhyeon/security/filter/JwtAuthenticationFilter.java
src/main/java/sopt/appjam/withsuhyeon/security/filter/JwtExceptionFilter.java
src/main/java/sopt/appjam/withsuhyeon/security/handler/JwtAuthenticationEntryPoint.java

♻️ [REFAC] 똥같은 시큐리티 코드 살짝 리팩터링

---

src/main/java/sopt/appjam/withsuhyeon/controller/PostController.java
src/main/java/sopt/appjam/withsuhyeon/service/PostService.java

✨ [FEAT] 전체 게시글 조회시 필터링 조건 변경

---

src/main/java/sopt/appjam/withsuhyeon/global/base/BaseTimeEntity.java

✨ [FEAT] 게시글 및 갤러리 작성 시 한국 표준시간으로 저장

---

src/main/java/sopt/appjam/withsuhyeon/exception/ConstantErrorCode.java
src/main/java/sopt/appjam/withsuhyeon/exception/PostErrorCode.java

:recycle: [REFAC] ErrorCode 리팩터링

---

src/main/java/sopt/appjam/withsuhyeon/config/CustomWebSocketHandler.java
src/main/java/sopt/appjam/withsuhyeon/repository/ChatRoomRepository.java

- closes #78 
- 소켓에서는 예외처리를 따로 모두 해줘야 되기에, 이 부분 리팩터링 필요합니다.

[REFAC] 의문의 기능 리팩터링

---

src/main/java/sopt/appjam/withsuhyeon/constant/Region.java

✨ [FEAT] Region ENUM 타입 추가

---

src/main/java/sopt/appjam/withsuhyeon/controller/AuthController.java
src/main/java/sopt/appjam/withsuhyeon/controller/BlockController.java
src/main/java/sopt/appjam/withsuhyeon/controller/PostController.java
src/main/java/sopt/appjam/withsuhyeon/domain/BlockEntity.java
src/main/java/sopt/appjam/withsuhyeon/domain/UserEntity.java
src/main/java/sopt/appjam/withsuhyeon/dto/auth/req/SignInRequestDto.java
src/main/java/sopt/appjam/withsuhyeon/dto/auth/req/SignUpRequestDto.java
src/main/java/sopt/appjam/withsuhyeon/dto/block/req/BlockNumberRequestDto.java
src/main/java/sopt/appjam/withsuhyeon/dto/post/req/PostRequestDto.java
src/main/java/sopt/appjam/withsuhyeon/dto/sms/req/CertificationPhoneNumberRequest.java
src/main/java/sopt/appjam/withsuhyeon/dto/sms/req/VerifyCertificationNumberRequest.java
src/main/java/sopt/appjam/withsuhyeon/service/AuthService.java
src/main/java/sopt/appjam/withsuhyeon/service/BlockService.java

[REFAC] 전화번호 정규 표현식 수정

---

src/main/java/sopt/appjam/withsuhyeon/config/CustomWebSocketHandler.java
src/main/java/sopt/appjam/withsuhyeon/domain/BlockEntity.java
src/main/java/sopt/appjam/withsuhyeon/domain/GalleryEntity.java
src/main/java/sopt/appjam/withsuhyeon/domain/PostEntity.java
src/main/java/sopt/appjam/withsuhyeon/domain/UserEntity.java
src/main/java/sopt/appjam/withsuhyeon/service/ChatRoomSaver.java

:recycle: [REFAC] @NotNull에서 @NotBlank로 어노테이션 변경
